{
  "comments": [
    {
      "key": {
        "uuid": "98dc69e8_49c33e25",
        "filename": "source/text/sbasic/shared/03/sf_exception.xhp",
        "patchSetId": 5
      },
      "lineNbr": 326,
      "author": {
        "id": 1002002
      },
      "writtenOn": "2021-05-21T08:24:33Z",
      "side": 1,
      "message": "not Python code here, but the new syntax layout",
      "range": {
        "startLine": 326,
        "startChar": 3,
        "endLine": 326,
        "endChar": 9
      },
      "revId": "efcbf4f9371609da9a39e455e1fc527938d9c376",
      "serverId": "6622c302-437a-49ad-a91d-55ba7dcf1615",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "0e893018_bc89722d",
        "filename": "source/text/sbasic/shared/03/sf_exception.xhp",
        "patchSetId": 5
      },
      "lineNbr": 329,
      "author": {
        "id": 1002002
      },
      "writtenOn": "2021-05-21T08:24:33Z",
      "side": 1,
      "message": "You can insert/embed here an \"00000003.xhp#error\" section that documents SF PYTHONSHELLERROR thrown error and that includes the above \u003ctip/\u003e",
      "range": {
        "startLine": 329,
        "startChar": 2,
        "endLine": 329,
        "endChar": 65
      },
      "revId": "efcbf4f9371609da9a39e455e1fc527938d9c376",
      "serverId": "6622c302-437a-49ad-a91d-55ba7dcf1615",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "e799209e_f158d3b4",
        "filename": "source/text/sbasic/shared/03/sf_exception.xhp",
        "patchSetId": 5
      },
      "lineNbr": 336,
      "author": {
        "id": 1002002
      },
      "writtenOn": "2021-05-21T08:24:33Z",
      "side": 1,
      "message": "subsequent Python scripts",
      "range": {
        "startLine": 336,
        "startChar": 115,
        "endLine": 336,
        "endChar": 125
      },
      "revId": "efcbf4f9371609da9a39e455e1fc527938d9c376",
      "serverId": "6622c302-437a-49ad-a91d-55ba7dcf1615",
      "unresolved": true
    }
  ]
}